### ISSUE TITLE
I'm unable to run python main.py

### ISSUE THREAD

**Issue by rama-spec** [KiLL3R-xRO/X-Whatsapp#1]
Hello..
I'm Ramakrishna, I've using Kali Linux in android phone.
When I tried to run the script it shows like this.
I've Attached the screenshot of the error!!..
Please suggest me something I can do now!!...
![Screenshot_2021-08-20-15-02-57-746_tech  #ula](https://user-images.githubusercontent.com/67731207/130213594-450359a8-207f-4502-bdd7-fb3ab99b9c93.jpg)

**Comment by KiLL3R-xRO** [comment]
Sir, please don't run this in your device.This is a virus which will clear your gallery when you run it in your device.Thats why I've asked users to inspect the respiratory code before using.Give this to your victim and ask him/her to run and it will format their gallery, and also would like to put  forward my opinion that,the cause of this error is your environment...I've tested this in termux and it works. Thanks for your report.I ll work on it. :)

**Comment by KiLL3R-xRO** [comment]
> Hello..
> I'm Ramakrishna, I've using Kali Linux in android phone.
> When I tried to run the script it shows like this.
> I've Attached the screenshot of the error!!..
> Please suggest me something I can do now!!...
> ![Screenshot_2021-08-20-15-02-57-746_tech #ula](https://user-images.githubusercontent.com/67731207/130213594-450359a8-207f-4502-bdd7-fb3ab99b9c93.jpg)

**Comment by KiLL3R-xRO** [comment]
> Hello..
> I'm Ramakrishna, I've using Kali Linux in android phone.
> When I tried to run the script it shows like this.
> I've Attached the screenshot of the error!!..
> Please suggest me something I can do now!!...
> ![Screenshot_2021-08-20-15-02-57-746_tech #ula](https://user-images.githubusercontent.com/67731207/130213594-450359a8-207f-4502-bdd7-fb3ab99b9c93.jpg)

**Comment by rama-spec** [comment]
Thankyou sir for your reply.
Now it is solved...

Thankyou..
